#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Resource {
    Clients,
    Invoices,
    Payments,
    Quotes,
    Credits,
    Vendors,
    Expenses,
    Projects,
    Tasks,
    Locations,
    Products,
    RecurringInvoices,
    PurchaseOrders,
    RecurringExpenses,
    BankTransactions,
    BankIntegrations,
    BankTransactionRules,
    ExpenseCategories,
    TaxRates,
    PaymentTerms,
    TaskStatuses,
    Activities,
    SystemLogs,
    Documents,
    Designs,
    Templates,
    Users,
    Companies,
    CompanyGateways,
    CompanyLedger,
    CompanyUsers,
    Tokens,
    Webhooks,
    Imports,
    Subscriptions,
    ClientGatewayTokens,
}

impl Resource {
    pub fn path(self) -> &'static str {
        match self {
            Self::Clients => "clients",
            Self::Invoices => "invoices",
            Self::Payments => "payments",
            Self::Quotes => "quotes",
            Self::Credits => "credits",
            Self::Vendors => "vendors",
            Self::Expenses => "expenses",
            Self::Projects => "projects",
            Self::Tasks => "tasks",
            Self::Locations => "locations",
            Self::Products => "products",
            Self::RecurringInvoices => "recurring_invoices",
            Self::PurchaseOrders => "purchase_orders",
            Self::RecurringExpenses => "recurring_expenses",
            Self::BankTransactions => "bank_transactions",
            Self::BankIntegrations => "bank_integrations",
            Self::BankTransactionRules => "bank_transaction_rules",
            Self::ExpenseCategories => "expense_categories",
            Self::TaxRates => "tax_rates",
            Self::PaymentTerms => "payment_terms",
            Self::TaskStatuses => "task_statuses",
            Self::Activities => "activities",
            Self::SystemLogs => "system_logs",
            Self::Documents => "documents",
            Self::Designs => "designs",
            Self::Templates => "templates",
            Self::Users => "users",
            Self::Companies => "companies",
            Self::CompanyGateways => "company_gateways",
            Self::CompanyLedger => "company_ledger",
            Self::CompanyUsers => "company_users",
            Self::Tokens => "tokens",
            Self::Webhooks => "webhooks",
            Self::Imports => "imports",
            Self::Subscriptions => "subscriptions",
            Self::ClientGatewayTokens => "client_gateway_tokens",
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            Self::RecurringInvoices => "recurring invoices",
            Self::PurchaseOrders => "purchase orders",
            Self::RecurringExpenses => "recurring expenses",
            Self::BankTransactions => "bank transactions",
            Self::BankIntegrations => "bank integrations",
            Self::BankTransactionRules => "bank transaction rules",
            Self::ExpenseCategories => "expense categories",
            Self::TaxRates => "tax rates",
            Self::PaymentTerms => "payment terms",
            Self::TaskStatuses => "task statuses",
            Self::SystemLogs => "system logs",
            Self::CompanyGateways => "company gateways",
            Self::CompanyLedger => "company ledger",
            Self::CompanyUsers => "company users",
            Self::ClientGatewayTokens => "client gateway tokens",
            _ => self.path(),
        }
    }

    pub fn upload_method(self) -> &'static str {
        match self {
            Self::Invoices => "PUT",
            _ => "POST",
        }
    }
}
